name: Publish stytch-android

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    check:
        name: Check versions and tags
        runs-on: ubuntu-latest
        outputs:
            tag_exists: ${{ steps.tags.outputs.tag_exists }}
            this_version: ${{ steps.version.outputs.this_version }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                distribution: zulu
                java-version: 17
                cache: 'gradle'
            - name: Get current version
              id: version
              run: |
                VERSION=$(./gradlew -q printVersion)
                echo "Found version $VERSION"
                echo "this_version=$VERSION" >> $GITHUB_OUTPUT
            - name: Check if tag exists
              id: tags
              run: |
                git fetch --tags
                echo "Checking for tags matching ${{ steps.version.outputs.this_version }}"
                TAG_EXISTS=false
                if [ $(git tag -l "${{ steps.version.outputs.this_version }}") ]; then
                    TAG_EXISTS=true
                fi
                echo "Tag exists = $TAG_EXISTS"
                echo "tag_exists=$TAG_EXISTS" >> $GITHUB_OUTPUT
    publish:
        name: Release build and publish
        needs: check
        if: needs.check.outputs.tag_exists == 'false'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              distribution: zulu
              java-version: 17
          - name: Clean
            run: ./gradlew clean
          - name: Release build
            run: ./gradlew :source:sdk:assembleRelease
          - name: Source jar
            run: ./gradlew :source:sdk:androidSourcesJar
          - name: Publish
            run: ./gradlew publish
          - name: Deploy
            run: ./gradlew jreleaserDeploy
            env:
              JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
              JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
              JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
              JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
              JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
    tag-and-release:
        name: Create tag and release
        runs-on: ubuntu-latest
        needs: check
        if: needs.check.outputs.tag_exists == 'false'
        steps:
            - uses: actions/checkout@v3
            - name: Create Tag
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --local user.name "CI"
                git config --local user.email "ci@stytch.com"
                git tag -a "${{needs.check.outputs.this_version}}" -m "${{needs.check.outputs.this_version}}"
                git push --follow-tags
            - name: Create Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release create "${{needs.check.outputs.this_version}}" --generate-notes
        
