# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: runOnGitHub
        env:
          STYTCH_PUBLIC_TOKEN: 'abc123'
          GOOGLE_OAUTH_CLIENT_ID: 'abc123'
          STYTCH_B2B_PUBLIC_TOKEN: 'abc123'
          STYTCH_B2B_ORG_ID: 'abc123'
          PASSKEYS_DOMAIN: 'abc123'
